services:
  nis:
    user: "${USERID:-1000}:${GROUPID:-1000}"
    container_name: nis
    build:
      context: ./docker/nis
      # args:
      #   VERSION: "0.6.102"
    ports:
      - "7778:7778"
      - "7890:7890"
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - ./data:/data/nem:rw
      # - ./config/nis/config-user.properties:/app/nem/nis/config-user.properties:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7890/heartbeat"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
