version: "3"
services:
  nis-client:
    user: "${USERID}:${GROUPID}"
    container_name: nis-client
    build:
      context: ./docker/nis-client
      args:
        - VERSION=0.6.100
    ports:
      - "7778:7778"
      - "7890:7890"
    restart: always
    stop_signal: SIGINT
    volumes:
      - ./data/nis-client:/app/nis-client/data:rw
      - ./config/nis-client/config-user.properties:/app/nis-client/nis/config-user.properties:ro
